<?php
//liste des 'correspondances collection <> domaine'
$DOMCOLL_LISTE = array(
0 => array('domaine'=>'spi', 'collhal'=>'FOTON'),
1 => array('domaine'=>'phys', 'collhal'=>'FOTON'),
2 => array('domaine'=>'spi', 'collhal'=>'IETR'),
3 => array('domaine'=>'info', 'collhal'=>'IETR'),
4 => array('domaine'=>'math', 'collhal'=>'IRMAR'),
5 => array('domaine'=>'stat', 'collhal'=>'IRMAR'),
6 => array('domaine'=>'info', 'collhal'=>'IRISA'),
7 => array('domaine'=>'sdv', 'collhal'=>'LTSI'),
8 => array('domaine'=>'sdv', 'collhal'=>'EMPENN-R'),
9 => array('domaine'=>'sdu', 'collhal'=>'GR'),
10 => array('domaine'=>'sde', 'collhal'=>'GR'),
11 => array('domaine'=>'phys', 'collhal'=>'IPR'),
12 => array('domaine'=>'chim', 'collhal'=>'ISCR'),
13 => array('domaine'=>'spi', 'collhal'=>'LGCGM'),
14 => array('domaine'=>'phys', 'collhal'=>'LGCGM'),
15 => array('domaine'=>'sdv', 'collhal'=>'U835'),
16 => array('domaine'=>'sdv', 'collhal'=>'BIOSIT'),
17 => array('domaine'=>'sdv', 'collhal'=>'CIC'),
18 => array('domaine'=>'sdv', 'collhal'=>'OSS'),
19 => array('domaine'=>'sdv', 'collhal'=>'CNGC'),
20 => array('domaine'=>'sde', 'collhal'=>'ECOBIO'),
21 => array('domaine'=>'sdu', 'collhal'=>'ECOBIO'),
22 => array('domaine'=>'sdv', 'collhal'=>'ECOBIO'),
23 => array('domaine'=>'scco', 'collhal'=>'ETHOS'),
24 => array('domaine'=>'sdv', 'collhal'=>'ETHOS'),
25 => array('domaine'=>'sde', 'collhal'=>'BIODIV'),
26 => array('domaine'=>'shs', 'collhal'=>'BIODIV'),
27 => array('domaine'=>'sdv', 'collhal'=>'IGDR'),
28 => array('domaine'=>'sdv', 'collhal'=>'IGEPP'),
29 => array('domaine'=>'sdv', 'collhal'=>'IRSET'),
30 => array('domaine'=>'sdv', 'collhal'=>'U917'),
31 => array('domaine'=>'sdv', 'collhal'=>'NUMECAN'),
32 => array('domaine'=>'sdv', 'collhal'=>'REPERES'),
33 => array('domaine'=>'shs', 'collhal'=>'CRAPE'),
34 => array('domaine'=>'shs', 'collhal'=>'PN'),
35 => array('domaine'=>'shs', 'collhal'=>'CDA-PR'),
36 => array('domaine'=>'shs', 'collhal'=>'CREAAH'),
37 => array('domaine'=>'shs', 'collhal'=>'CREM'),
38 => array('domaine'=>'shs', 'collhal'=>'IODE'),
39 => array('domaine'=>'shs', 'collhal'=>'IDPSP'),
40 => array('domaine'=>'shs', 'collhal'=>'M2S'),
41 => array('domaine'=>'sdv', 'collhal'=>'M2S')
);
?>